export const LOAD_SCHEDULE = 'LOAD_SCHEDULE';
export const CHANGE_SCHEDULE_TABLE = 'CHANGE_SCHEDULE_TABLE';
export const MARK_ALL_DAY = 'MARK_ALL_DAY';
export const UNMARK_ALL_DAY = 'UNMARK_ALL_DAY';
export const TRANSFORM_DATA = 'TRANSFORM_DATA';
export const CHANGE_SCHEDULE_TABLE_MOUSE_MOVE = 'CHANGE_SCHEDULE_TABLE_MOUSE_MOVE';
// //////////////////////////////////////////
export const LOAD_EVENTS_SUCCESS = 'LOAD_EVENTS_SUCCESS';
export const LOAD_EVENTS_FAILURE = 'LOAD_EVENTS_FAILURE';
